[[plugins]]
repo = 'hotchpotch/perldoc-vim'
on_ft = ['perl']

[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = ['python', 'python3', 'djangohtml']

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python', 'python3', 'djangohtml']

[[plugins]]
repo = 'davidhalter/jedi-vim'
depends = 'deoplete.nvim'
on_ft = ['python', 'python3', 'djangohtml']
hook_post_source = '''
autocmd vimrc FileType python setlocal omnifunc=jedi#completions
let g:jedi#force_py_version = 3
let g:jedi#completions_enabled = 0
let g:jedi#auto_vim_configuration = 0
let g:jedi#popup_select_first = 0
let g:jedi#rename_command = '<Leader>R'
if !exists('g:neocomplete#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {}
endif
let g:neocomplete#force_omni_input_patterns.python =
    \ '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'
'''

[[plugin]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python', 'python3', 'djangohtml']

[[plugins]]
repo = 'cjrh/vim-conda'

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']


[[plugins]]
repo  = 'leafgarland/typescript-vim'
on_ft = ['typescript']
hook_post_source = '''
let g:typescript_indent_disable = 1
let g:typescript_compiler_binary = 'tsc'
let g:typescript_compiler_options = ''
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = [ 'nvim-yarp', 'vim-hug-neovim-rpc' ]
on_i = 1
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo  = 'posva/vim-vue'
on_ft = ['vue']
